# Generated by Django 5.0.6 on 2024-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_student_book_borrowed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_by',
            field=models.ManyToManyField(blank=True, related_name='books_borrowed', to='LMS.student'),
        ),
    ]
